### ISSUE TITLE
🐛[BUG]: `Module.from_torch()` produces incomplete `__init__` signature (missing keyword-only arguments)

### ISSUE THREAD

**Issue by giprayogo** [NVIDIA/physicsnemo#1349]
### Version

1.4.0a0 (same problem in 1.3.0)

### On which installation method(s) does this occur?

Pip

### Describe the issue

I was trying to convert existing PyTorch model into PhysicsNeMo (CHGNet) using `Module.from_torch()`, but I got `TypeError: got an unexpected keyword argument ...` when trying to initialize the model.

After looking into it, I found that `Module.from_torch()` drops keyword-only arguments from the constructor. This is because the signature replacement logic only reads `args` and `defaults` from `FullArgSpec`, ignoring other fields including `kwonlyargs` and `kwonlydefaults` that contains the keyword-only arguments:

https://github.com/NVIDIA/physicsnemo/blob/8d8b1ed6edf5e2fdeace46d285ecf06792d9cea7/physicsnemo/core/module.py#L1261-L1283

First introduced in #65.

Perhaps this is also related to issue #1169?

I found that taking the `__init__` signature as-is solves the problem (without breaking existing tests):

```python
# Replace PhysicsNeMoModel.__init__ signature with torch model signature
PhysicsNeMoModel.__init__.__signature__ = inspect.signature(
    torch_model_class.__init__
)
```

I wonder if this is intentional, or if there's a design consideration I might have missed?

If this is indeed a bug, I'd be happy to open a PR with the fix.

### Minimum reproducible example

```shell
import torch.nn as nn

from physicsnemo.core import Module


class SimpleMLP(nn.Module):
    def __init__(self, *, input_size=10, hidden_size=64, output_size=5):
        super().__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


PNMSimpleMLP = Module.from_torch(SimpleMLP)
PNMSimpleMLP(input_size=10, hidden_size=64, output_size=5)
```

### Relevant log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipython-input-3212150548.py in <cell line: 0>()
     20 
     21 PNMSimpleMLP = Module.from_torch(SimpleMLP)
---> 22 PNMSimpleMLP(input_size=10, hidden_size=10, output_size=10)

/usr/local/lib/python3.12/dist-packages/physicsnemo/core/module.py in __new__(cls, *args, **kwargs)
    181 
    182         # Bind args and kwargs to signature
--> 183         bound_args = sig.bind_partial(
    184             *([None] + list(args)), **kwargs
    185         )  # Add None to account for self

/usr/lib/python3.12/inspect.py in bind_partial(self, *args, **kwargs)
   3285         Raises `TypeError` if the passed arguments can not be bound.
   3286         """
-> 3287         return self._bind(args, kwargs, partial=True)
   3288 
   3289     def __reduce__(self):

/usr/lib/python3.12/inspect.py in _bind(self, args, kwargs, partial)
   3267                 )
   3268             else:
-> 3269                 raise TypeError(
   3270                     'got an unexpected keyword argument {arg!r}'.format(
   3271                         arg=next(iter(kwargs))))

TypeError: got an unexpected keyword argument 'input_size'
```

### Environment details

```shell

```

**Comment by CharlelieLrt** [comment]
@giprayogo good catch, thanks for reporting this! I think the solution you proposed can work. Can you open a PR please? On my side I'll also look for other edge cases that might not be totally covered.

Regarding #1169 I think the issue is different. It seems to come from a clash between Module's names in the main script and the registry. As a result the class-resolution logic would pick up the wrong class, which is not expecting the same arguments. But this should also be resolved, as we hae deprecated the `name` field in the metadata (more tests pending there as well).

**Comment by CharlelieLrt** [comment]
@giprayogo just following up on this. Were you able to open a PR with your proposed fix?
